export default {
  projects: [
    {
      id: 1,
      name: "Car Meet-Up",
      image: "../image/car-meet.png",
      description:
        "A flask application for car enthusiasts to find or host their own events. Has user login authentication and CRUD operations. Implemented Cloudinary API to upload pictures and Google Maps to update and display markers on meet up locations.",
      tech: "Python, PostgreSQL, SQL Alchemy, Flask, Jinja, HTML, CSS, JavaScript",
      github: "https://github.com/vsvang87/car-meet",
      video: "https://youtu.be/gfzCajv79zE",
      category: "Full-Stack",
    },
    {
      id: 2,
      name: "Hmong First Baptist Church",
      image: "../image/church1.jpg",
      description:
        "A single page responsive website to display their ministries, services, and worship hours. Implemented with stripe payment gateway for donations.",
      tech: "React, Sass, Stripe",
      site: "https://hfbc.netlify.app/",
      github: "https://github.com/vsvang87/hfbc_church",
      category: "React",
    },
    {
      id: 3,
      name: "Password Generator",
      image: "../image/passwordgenerator.png",
      description:
        "A password generator app that will generate a random password for you.",
      tech: "HTML, CSS, JavaScript",
      site: "https://visaypasswordgenerator.netlify.app/",
      github: "https://github.com/vsvang87/Password-Generator/tree/master",
      category: "JavaScript",
    },
    {
      id: 4,
      name: "Recipe Finder",
      image: "../image/recipe.png",
      description: "A recipe app to search any recipes of your choice.",
      tech: "HTML, CSS, JavaScript(AJAX)",
      site: "https://visayrecipeapp.netlify.app",
      github: "https://github.com/vsvang87/RecipeApp/tree/master",
      category: "JavaScript",
    },
    {
      id: 5,
      name: "Search Movie",
      image: "../image/movieapp.jpg",
      description:
        "Movie web app that allows you to search any movie of your choice. It'll display the year, rating and a brief description of that movie.",
      tech: "React, Sass",
      site: "https://visaysearchmovie.netlify.app/",
      github: "https://github.com/vsvang87/search_movie_app/tree/master",
      category: "React",
    },
    {
      id: 6,
      name: "Nike Clone Site",
      image: "../image/nikeclone.jpg",
      description: "Re-created Nike website.",
      tech: "HTML, Sass",
      site: "https://visaynikeclone.netlify.app/",
      github: "https://github.com/vsvang87/nike_clone/tree/master",
      category: "LandingPage",
    },
    {
      id: 7,
      name: "T-Mobile Clone Site",
      image: "../image/t-mobile-clone.jpg",
      description: "Re-created T-Mobile website.",
      tech: "HTML, Sass",
      site: "https://visaytmobileclone.netlify.app/",
      github: "https://github.com/vsvang87/t-mobile_clone/tree/master",
      category: "LandingPage",
    },
    {
      id: 8,
      name: "Promotional",
      image: "../image/lids.jpg",
      description: "Responsive Promotional Email from Lids.",
      tech: "HTML",
      site: "https://lidshtmlemail.netlify.app",
      github: "https://github.com/vsvang87/LidsHtml/tree/master",
      category: "HTMLEmail",
    },
    {
      id: 9,
      name: "News Letter",
      image: "../image/creditkarma.jpg",
      description: "Responsive News Letter Email.",
      tech: "HTML",
      site: "https://creditkarmhtmlemail.netlify.app",
      github: "https://github.com/vsvang87/creditkarma/tree/master",
      category: "HTMLEmail",
    },
    {
      id: 10,
      name: "Transactional",
      image: "../image/transactional.jpg",
      description: "Responsive transactional email from Dominos.",
      tech: "HTML",
      site: "https://dominotransaction.netlify.app/",
      github: "https://github.com/vsvang87/Domino_Transactional/tree/master",
      category: "HTMLEmail",
    },
  ],
};
